name: tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  change_case: ^1.1.0
  get: ^4.6.5
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
